global:
  resolve_timeout: 5m

route:
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 1h
  receiver: 'email-team'

receivers:
  - name: 'email-team'
    email_configs:
      - to: 'you@example.com'
        from: 'monitor@example.com'
        smarthost: smtp.example.com:587
        auth_username: 'monitor@example.com'
        auth_password: 'yourpassword'
        require_tls: true
