global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'telemedicine-backend'
    static_configs:
      - targets: ['telemedicine-appauthfinalprom-grafan_backend:8000']

  - job_name: 'telemedicine-frontend'
    static_configs:
      - targets: ['telemedicine-appauthfinalprom-grafan_frontend:8501']
